### ISSUE TITLE
languages.json is missing, if you don't git clone with `--recursive`

### ISSUE THREAD

**Issue by marcindulak** [Alir3z4/python-stop-words#14]
languages.json is still missing, if you don't clone with `--recursive`

$ git clone git://github.com/Alir3z4/python-stop-words.git
$ cd python-stop-words
$ python3 setup.py install
 Traceback (most recent call last):
  File "setup.py", line 5, in <module>
    version=__import__("stop_words").get_version(),
  File "./stop_words/__init__.py", line 9, in <module>
    with open(os.path.join(STOP_WORDS_DIR, 'languages.json'), 'rb') as map_file:
FileNotFoundError: [Errno 2] No such file or directory: './stop_words/stop-words/languages.json'

**Comment by Alir3z4** [comment]
That's true, thanks for reporting this.
