### ISSUE TITLE
can you handle a text？

### ISSUE THREAD

**Issue by IamMegatron2025** [Alir3z4/python-stop-words#18]
hello, no description about how to use. Now I have a text:
`The University of Waterloo Stratford Campus is located in Stratford Ontario Canada. It is one of the three satellite campuses of the University of Waterloo a member of the U15 Group of Canadian Research Universities.Established in June 2009 the University of Waterloo Stratford Campus is part of the Faculty of Arts at the University of Waterloo.`
how to use `python-stop-words` to filter the stop-words to get a text without stop-words?

thank you very much!!

**Comment by DadImScared** [comment]
Hello. Does this example help? [https://hastebin.com/agopezejak.py](https://hastebin.com/agopezejak.py)

**Comment by IamMegatron2025** [comment]
@DadImScared that is cool. thank you
