### ISSUE TITLE
how to add/remove custom  stopword

### ISSUE THREAD

**Issue by dipenpatel235** [Alir3z4/python-stop-words#19]
how to add/remove custom  stopword from list ?

**Comment by Alir3z4** [comment]
Could you explain the usage of such feature please ?

**Comment by dipenpatel235** [comment]
for example your stop word list is
['which','who','hello','school']

now in that i need to add my own word 'college' as stop word  so how i can add that words.
second thing suppose i want to remove 'school' from stop word list so how i can remove that word.

let me know if still not clear...

Usage: for custom word add/ remove purpose. because such word are not useful to me
Thanks

**Comment by Alir3z4** [comment]
Great, I get it now, thanks for the clarification.
It's possible with the current implementation, a stop word for each language is simply a Python `list` of `str` which you can easily manipulate.

For instance:
```python

from stop_words import get_stop_words

stop_words = get_stop_words('en')  # returns a List[str]
stop_words.extend[['which','who','hello','school']]
```
as with removal as well.

That would do it, right ?

**Comment by dipenpatel235** [comment]
yes for add and remove.
but that extend/remove list need to do one time to add in your stop word list file.
later i not need to required maintain extend list

**Comment by Alir3z4** [comment]
The source of stop words are coming from file system, it cannot be extended in that way.
Although there might be a room for improvement to be able to feed more stop words into the `stop_words` package and maintain the new/modified stop words, however that would add extra complexity to the library and overhead which to be honest it's not necessary.

I think the best way for your purpose would be to wrap the `stop_words` in a class that maintains the state of the list through the lifetime of the program.

**Comment by dipenpatel235** [comment]
okey...
that is also fine.

Thanks for your valuable time.

**Comment by Alir3z4** [comment]
Awesome, I'll close the issue.
Feel free to re-open or make new issues if anything comes up.
