### ISSUE TITLE
cannot install

### ISSUE THREAD

**Issue by cjauvin** [Alir3z4/python-stop-words#9]
No matter how I try to install (pip, git clone, etc) I always get the error that `languages.json` is missing.

**Comment by Alir3z4** [comment]
I'll fix this soon, probably in couple of hours ;)

thanks.

**Comment by cjauvin** [comment]
Thanks for the quick reply!

**Comment by Alir3z4** [comment]
Fixed: https://github.com/Alir3z4/python-stop-words/releases/tag/2015.2.23.1
